### PR TITLE
Fixed indentation of several configuration and initialization files

### LINKED ISSUE #18: Incorrect formatting on development.rb
screen shot 2017-02-03 at 16 34 35

### PR DESCRIPTION
**Pull request by fjsanpedro**
Fixes #18

### CODE REVIEW

File: recipes/sidekiq.rb [hunk 1]
```diff
@@ -31,20 +31,20 @@ def init_file
...
-      @template.insert_into_file 'config/routes.rb', before: "Rails.application.routes.draw do\n" do <<-RUBY
-        require 'sidekiq/web'
-        RUBY
+      @template.insert_into_file 'config/routes.rb', before: "Rails.application.routes.draw do\n" do <<~RUBY
+      require 'sidekiq/web'
+      RUBY
       end
 
-      @template.insert_into_file 'config/routes.rb', after: "Rails.application.routes.draw do\n" do <<-RUBY
+      @template.insert_into_file 'config/routes.rb', after: "Rails.application.routes.draw do\n" do <<~RUBY
```
Comment (xredo) [inline recipes/sidekiq.rb:39]: Use single quotes

**Review by xredo — CHANGES_REQUESTED** [review]
